### ISSUE TITLE
filtering reflected tables?

### ISSUE THREAD

**Issue by BadToast** [arthurio/fastapi-filter#168]
Hello @arthurio , this is more of a question than an issue.

The examples shown seem to assume that you know and can dictate the schema.  What about reflected tables?  Here's some minimal code to illustrate:

```python
class CustomerFilter(Filter):
    customer: str = Field(Query(default = "123456"))
#    class Constants(Filter.Constants):
#        model = Customer
#    Some sort of reflected model needs to go here?  do we dump a reflected
#    schema from the table and reproduce it?

@router.get("/filter-reflected-table/")
async def filter_reflected_table(
    customer_filter: CustomerFilter = FilterDepends(CustomerFilter, by_alias=True)
):
    meta = MetaData()
    engine = create_engine(DB_URL)
    table = Table(SOME_TABLE, meta, autoload_with=engine)  # table reflected here
    query = select(table).filter(table.c.customer == "123456")  # this works
    query = customer_filter.filter(query)  # this dies
    with Session(engine) as session:
        result = session.execute(query)
        return result.fetchall()
```

The traceback cries about the Constants not being defined, here's a snippet:
```python
    query = customer_filter.filter(query)  # this dies
  File "/usr/local/envs/fastapi/lib/python3.9/site-packages/fastapi_filter/base/filter.py", line 214, in filter
    return original_filter.filter(*args, **kwargs)
  File "/usr/local/envs/fastapi/lib/python3.9/site-packages/fastapi_filter/contrib/sqlalchemy/filter.py", line 89, in filter
    model_field = getattr(self.Constants.model, field_name)
AttributeError: type object 'Constants' has no attribute 'model'
```

So my question is how do we construct the filter class "correctly" to work with a table that's reflected from some other DB?  As per the comments, is there a way to pass a reflected model that gets filled at runtime?  Do we have to dump the reflected model and re-declare it manually in order to be able to use it?  The latter seems like a bad practice, but if that's the only way, what is the correct way?

**Comment by arthurio** [comment]
Hi @BadToast , sorry for the long delay before replying!
I'm not super familiar with reflected tables so thank you for the example it helps a lot.
So yes the filter class has to access the model through it's `Constant` subclass in order to work.
Now in your example, you declare your table inside the endpoint which I don't think is a good practice, otherwise you'll end up invoking that code on every request. Did you try to create your reflected table outside of the endpoint and setup your filter afterwards? Something like:

```python
# Somewhere near where you define your FastAPI.App
meta = MetaData()
engine = create_engine(DB_URL)
CustomerTable = Table("customers", meta, autoload_with=engine)  # table reflected here


# Somewhere else, e.g. `filters.py`
from . import CustomerTable

class CustomerFilter(Filter):
    customer: str = Field(Query(default = "123456"))
    class Constants(Filter.Constants):
        model = CustomerTable

@router.get("/filter-reflected-table/")
async def filter_reflected_table(
    customer_filter: CustomerFilter = FilterDepends(CustomerFilter, by_alias=True)
):
    query = select(table).filter(table.c.customer == "123456")  # this works
    query = customer_filter.filter(query)  # this should work as long as `customer` is the right field name to access?
    with Session(engine) as session:
        result = session.execute(query)
        return result.fetchall()
```

**Comment by arthurio** [comment]
@BadToast Thanks for reporting back. I guess we would have to detect the type of model/table passed to the filter and access the attributes differently for generated ones (using reflection). So I think it's technically possible but requires some dig in.
I'm glad that you end up with something that will work for you and I'm sure that you'll see a lot of benefits from having explicitly defined models in your code. From a quick google search you might want to look at https://github.com/agronholm/sqlacodegen to help you generate your models initially, then you can tweak manually.

Let's close this issue for now and we can revisit if someone cannot do without reflected tables.
